export const NS = 'settings.loongport'

export const en = {
  nav: 'LoongPort',
  title: 'LoongPort providers',
  loading: 'Loading signed provider directory…',
  directoryUnavailable: 'The signed LoongPort provider directory is temporarily unavailable.',
  refresh: 'Refresh directory',
  manualSetup: 'Set up manually',
  configure: 'Configure provider',
  clearKey: 'Clear API key',
  configured: 'API key configured',
  notConfigured: 'API key not configured',
  disabled: 'Unavailable',
  registration: 'Registration / login',
  sponsorship: 'Disclosure',
  model: 'Selected model',
  availableModels: 'Available models',
  invitationCode: 'Invitation / promotion code',
  observation: 'VeriDrop observation',
  rank: 'Rank',
  score: 'Score',
  report: 'Open report',
  manualTitle: 'Enter API key manually',
  manualDescription: 'Paste a key generated by this provider. It is saved by DSH credentials and is not stored in this page.',
  apiKey: 'API key',
  save: 'Save and configure',
  cancel: 'Cancel',
  saveFailed: 'The API key could not be saved. Check the key and try again.',
}

export const zh = {
  nav: 'LoongPort',
  title: 'LoongPort 服务商',
  loading: '正在加载已签名的服务商目录…',
  directoryUnavailable: '已签名的 LoongPort 服务商目录暂时不可用。',
  refresh: '刷新目录',
  manualSetup: '手动配置',
  configure: '配置服务商',
  clearKey: '清除 API 密钥',
  configured: '已配置 API 密钥',
  notConfigured: '未配置 API 密钥',
  disabled: '暂不可用',
  registration: '注册 / 登录',
  sponsorship: '披露信息',
  model: '已选模型',
  availableModels: '可用模型',
  invitationCode: '邀请码 / 优惠码',
  observation: 'VeriDrop observation',
  rank: '排名',
  score: '评分',
  report: '打开报告',
  manualTitle: '手动输入 API 密钥',
  manualDescription: '请粘贴由此服务商生成的密钥。密钥由 DSH 凭据服务保存，不会存储在本页面中。',
  apiKey: 'API 密钥',
  save: '保存并配置',
  cancel: '取消',
  saveFailed: '无法保存 API 密钥。请检查密钥后重试。',
}

export type LoongPortLocaleKey = keyof typeof en

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    'settings.loongport': LoongPortLocaleKey
  }
}
